# 1 = green
# 4 = yellow
# 5 = red
---
 board:
 # RED AND YELLOW
  0: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 4}
  1: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 3}
  2: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 2}
  3: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 1}
  4: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 1}
  5: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 2}
  6: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 3}
  7: { "flavor_id": 4, interface: "Adafruit_PCA9685", distance: 4}
  8: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 4}
  9: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 3}
  10: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 2}
  11: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 1}
  12: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 1}
  13: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 2}
  14: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 3}
  15: { "flavor_id": 5, interface: "Adafruit_PCA9685", distance: 4}
  # GREEN LEDS
  16: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 8}
  17: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 7}
  18: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 6}
  19: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 5}
  20: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 4}
  21: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 3}
  22: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 2}
  23: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 1}
  24: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 1}
  25: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 2}
  26: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 3}
  27: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 4}
  28: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 5}
  29: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 6}
  30: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 7}
  31: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 8}
  31: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 8}
  # MOTORS
  # 32: { "flavor_id": 12, interface: "Adafruit_PCA9685", distance: 1}
  32: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  33: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  34: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  35: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  36: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  36: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  37: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  38: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  39: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  40: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  41: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  42: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  43: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 1}
  44: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 2}
  45: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 3}
  46: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 4}
  47: { "flavor_id": 2, interface: "Adafruit_PCA9685", distance: 5}
